"""initial schema: companies and job_postings

Revision ID: e50e9fd56fdf
Revises: 
Create Date: 2026-06-19 12:42:08.883710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e50e9fd56fdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('size_range', sa.String(), nullable=True),
    sa.Column('hq_location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=False),
    sa.Column('seniority', sa.String(), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=False),
    sa.Column('description_cleaned', sa.Text(), nullable=False),
    sa.Column('role_cluster', sa.String(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embedding_id', sa.String(), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_postings_company_id', 'job_postings', ['company_id'], unique=False)
    op.create_index('ix_job_postings_is_active', 'job_postings', ['is_active'], unique=False)
    op.create_index('ix_job_postings_role_cluster', 'job_postings', ['role_cluster'], unique=False)
    op.create_index('ix_job_postings_seniority', 'job_postings', ['seniority'], unique=False)
    op.create_index('ix_job_postings_source', 'job_postings', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_postings_source', table_name='job_postings')
    op.drop_index('ix_job_postings_seniority', table_name='job_postings')
    op.drop_index('ix_job_postings_role_cluster', table_name='job_postings')
    op.drop_index('ix_job_postings_is_active', table_name='job_postings')
    op.drop_index('ix_job_postings_company_id', table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_table('companies')
    # ### end Alembic commands ###
